# Generated by Django 2.0.6 on 2018-06-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
